CREATE TABLE Cities(
CityID INT PRIMARY KEY NOT NULL,
Name VARCHAR(50) NOT NULL
)

CREATE TABLE ItemTypes(
ItemTypeID INT PRIMARY KEY NOT NULL,
Name VARCHAR(50) NOT NULL,
)

CREATE TABLE Customers(
CustomerID INT PRIMARY KEY NOT NULL,
Name VARCHAR(50) NOT NULL,
Birthday DATE,
CityID INT NOT NULL,
CONSTRAINT FK_CityID FOREIGN KEY (CityID) REFERENCES Cities(CityID)
)

CREATE TABLE Items(
ItemID INT PRIMARY KEY NOT NULL,
Name VARCHAR(50) NOT NULL,
ItemTypeID INT NOT NULL,
CONSTRAINT FK_ItemTypeID FOREIGN KEY (ItemTypeID) REFERENCES ItemTypes(ItemTypeID)
)

CREATE TABLE Orders (
OrderID INT NOT NULL,
CustomerID INT NOT NULL,
CONSTRAINT PK_Orders PRIMARY KEY(OrderID),
CONSTRAINT FK_CustomerID FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID)
)

CREATE TABLE OrderItems (
OrderID INT NOT NULL,
ItemID INT NOT NULL,
CONSTRAINT PK_OrderItems PRIMARY KEY(OrderID,ItemID),
CONSTRAINT FK_ItemID FOREIGN KEY (ItemID) REFERENCES Items(ItemID),
CONSTRAINT FK_OrderID FOREIGN KEY (OrderID) REFERENCES Orders(OrderID)

)

